services:
  postgres:
    image: postgres:16
    container_name: VicaPostgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: database
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  vica-bek:
    build:
      context: .
      dockerfile: Dockerfile
    image: vica-front-image
    container_name: VicaFront
    env_file:
      - .env
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      NODE_OPTIONS: --max-old-space-size=1024
      SITE_URL: ${SITE_URL}
      INSTAGRAM_ACCESS_TOKEN: ${INSTAGRAM_ACCESS_TOKEN}
      INSTAGRAM_IG_USER_ID: ${INSTAGRAM_IG_USER_ID}
    ports:
      - "3003:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - postgres
    restart: unless-stopped

    command: sh -lc "
      echo 'Pushing Prisma schema...';
      until npx prisma db push; do
        echo 'DB not ready yet, retrying in 2s...';
        sleep 2;
      done;
      echo 'Starting Next.js...';
      npm start"

volumes:
  postgres_data:
